uploads = []
outputs = []

[[generated]]
id = "Xk6qLkOz9Yrwcl7uZpGFT"
uri = "file://public/images/usecase-finance.png"
type = "image"
title = "bright finance illustration"

[[generated]]
id = "VDhBNYctjDSDVHVKwPawr"
uri = "file://public/images/usecase-compliance.png"
type = "image"
title = "bright compliance illustration"

[[generated]]
id = "0YvS-15h-p1_e2IOIs7Pt"
uri = "file://public/images/usecase-hr.png"
type = "image"
title = "bright HR illustration"

[[generated]]
id = "mX9sCzrP6UGFjsCcrSFe5"
uri = "file://public/images/usecase-reporting.png"
type = "image"
title = "bright reporting illustration"
